[package]
name = "contracts"
version = "0.1.0"
edition = "2023_11"
rpc_url = ""

[workspace]
members = ["deploy"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.19.0" }
starknet = "2.5.4"

[[target.starknet-contract]]
casm = true

[lib]
sierra = true
casm = true