[package]
name = "contracts"
version = "0.2.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "=2.8.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }


[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true

[lib]
casm = true

[workspace]
members = ["scripts"]