[package]
name = "cairoscripts"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }
starknet = ">=2.6.3"
contracts = { path = "../" }

[lib]
sierra = true
casm = true


[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "contracts::*"
]


