[package]
name = "deploy_script"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.35.1" }
starknet = ">=2.9.2"
contracts = { path = "/Users/zhengpeng/Source/Code/Rust-Code/Github/scaffold-stark-2/packages/snfoundry/contracts" }

[lib]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
build-external-contracts = [
    "contracts::*"
]

