name: Next.js CI

on:
  push:
    paths:
      - "packages/snfoundry/contracts/**"
      - "packages/nextjs/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "packages/nextjs/**"
      - "packages/snfoundry/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies (Next.js)
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      - name: Install snfoundryup
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./.tool-versions

      - name: Build Contracts
        run: yarn compile

      - name: Run smart contract tests
        run: yarn test

      - name: Check Code Format
        run: yarn format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Run Next.js tests
        run: yarn test
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: yarn build
        working-directory: ./packages/nextjs
