name: Next.js CI

on:
  push:
    paths:
      - "packages/snfoundry/contracts/**"
      - "packages/nextjs/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"
      - "packages/snfoundry/contracts/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.9.2

      - name: Install snfoundryup
        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh

      - name: Install snforge
        run: snfoundryup -v 0.35.1

      - name: Run snforge tests
        run: snforge test
        working-directory: ./packages/snfoundry/contracts

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          #cache-dependency-path: packages/nextjs/yarn.lock

      - name: Install dependencies (Next.js)
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Check Code Format
        run: yarn format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Run Next.js tests
        run: yarn test run
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: yarn build
        working-directory: ./packages/nextjs
